# User-Server Port 지정
server:
  port: 8081

# Spring Server Settings
spring:
  application:
    name: member-service

  # Database Connection
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/astaro?characterEncoding=UTF-8&amp&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: a604
    password: a604ssafy

  # JPA Settings
  jpa:
    database: mysql
    hibernate:
      ddlAuto: none
      useNewIdGeneratorMappings: true
    generateDdl: true
    databasePlatform: org.hibernate.dialect.MySQL8Dialect

# Eureka Client Settings
eureka:
  instance:
    hostname: 172.17.0.1
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
