# Gateway Server Port 지정
server:
  port: 8000
  
# Eureka Client 등록 : serviceUrl은 향후에 수정
eureka:
  client:
    registerWithEureka: true
    fetchregistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

# MSA ROuting & Filter 적용
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      # CORS 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://k8a604.p.ssafy.io,http://astaro.co.kr,https://k8a604.p.ssafy.io,https://astaro.co.kr,http://localhost:3000"
            allowedHeaders: "*"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        # Member Service Auth 컨트롤러
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/auth/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # Member Service 그외 나머지
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - JwtAuthenticationFilter
            - name: JwtAuthorizationFilter
              args:
                role: ROLE_USER
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # Taro Service
        - id: taro-service
          uri: lb://TARO-SERVICE
          predicates:
            - Path=/taro-service/**
          filters:
            - JwtAuthenticationFilter
            - name: JwtAuthorizationFilter
              args:
                role: ROLE_USER
            - RewritePath=/taro-service/(?<segment>.*), /$\{segment}
        # Board Service
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - JwtAuthenticationFilter
            - name: JwtAuthorizationFilter
              args:
                role: ROLE_USER
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}

jwt.secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa