# Gateway Server Port 지정
server:
  port: 8000
  
# Eureka Client 등록 : serviceUrl은 향후에 수정
eureka:
  client:
    registerWithEureka: true
    fetchregistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

# MSA ROuting & Filter 적용
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        # Member Service Auth 컨트롤러
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/auth/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # Member Service 그외 나머지
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        # Taro Service
        - id: taro-service
          uri: lb://TARO-SERVICE
          predicates:
            - Path=/taro-service/**
          filters:
            - RewritePath=/taro-service/(?<segment>.*), /$\{segment}
        # Board Service
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/**
          filters:
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}